### ISSUE TITLE
Remove existing //# sourceMappingURL comments

### ISSUE THREAD

**Issue by bbrouwer** [gulp-sourcemaps/gulp-sourcemaps#24]
If I concatenate a bunch of files together that already have sourceMap comments, I would like the original //# sourceMappingURL comments to be removed. For this configuration

```
return gulp.src([
      paths.bower + 'jquery/dist/jquery.min.js',
      paths.bower + 'angular/angular.min.js'])
  .pipe(sourcemaps.init({loadMaps: true}))
  .pipe(concat('out.js'))
  .pipe(sourcemaps.write('.'))
  .pipe(gulp.dest(paths.dist + 'scripts'));
```

The resulting out.js looks like this:

```
// jquery stuff
//# sourceMappingURL=jquery.min.map

// angular stuff
//# sourceMappingURL=angular.min.js.map

//# sourceMappingURL=out.js.map
```

Wouldn't it be better if out.js looked like this:

```
// jquery stuff
// angular stuff
//# sourceMappingURL=out.js.map
```

Is there a better approach that I should be using?

**Comment by jmeas** [comment]
I'm still observing this with a file produced by [esperantojs](https://github.com/esperantojs/esperanto).

The input file has an inlined map, and the output is...

```js
//# sourceMappingURL=data:application/json;charset=...
//# sourceMappingURL=library-dist.js.map
```

Try it yourself by pulling down [this branch of this library](https://github.com/jmeas/es6-library-boilerplate/pull/57), then:

```sh
npm install && gulp build:esperanto
```

Look at the file output in `dist`.

**Comment by jmeas** [comment]
This may actually be a problem with [convert-source-map](https://github.com/thlorenz/convert-source-map/blob/master/index.js#L5).
