### ISSUE TITLE
Document how to manage 1.x and 2.x branches together

### ISSUE THREAD

**Issue by phated** [gulp-sourcemaps/gulp-sourcemaps#287]
@nmccready I just realized that I don't know how you manage the 2 branches of code together.  Can you document here?

**Comment by nmccready** [comment]
Sure, in a nutshell I do all the changes currently on the 1.X branch first as they easily roll up to 2.X . The only thing making 2.X (master) any different is it's dependency on `strip-bom` (new one  requires node >=4).

- https://github.com/floridoo/gulp-sourcemaps/blob/1.X/package.json#L33
- https://github.com/floridoo/gulp-sourcemaps/blob/master/package.json#L33

So 1.X is catering to older versions of node support. So to eliminate the headache we could drop `strip-bom` and use something else.

**Comment by nmccready** [comment]
Currently to limit headaches all the code is in ES5 as well. So if we're dying to get onto ES6 I guess we could use babel for older versions of Node.

**Comment by phated** [comment]
Cool. Thanks. Definitely not interested in ES6 (given up on that nightmare).

**Comment by phated** [comment]
Closing as I think this has been fully answered.  Will reopen and comment if I have any troubles.
