### ISSUE TITLE
Possibly consider other options for css processing

### ISSUE THREAD

**Issue by nmccready** [gulp-sourcemaps/gulp-sourcemaps#290]
@phated I just wanted to make a note here that we should possibly consider something other than [css](https://github.com/reworkcss/css) for doing our css mapping. It has numerous problems and does not seem to be very active. It is responsible for many of the closed bugs that relate to sass and css mapping problems.

**Comment by phated** [comment]
Moved to gulp-sourcemaps/identity-map/issues/1
