### ISSUE TITLE
'gulp-sourcemaps/map-sources' is not in the npm registry.

### ISSUE THREAD

**Issue by lasotaartur** [gulp-sourcemaps/gulp-sourcemaps#293]
Today I have problem like below:
```
 error 404 Not Found
4121 error 404
4121 error 404 'gulp-sourcemaps/map-sources' is not in the npm registry.
4121 error 404 You should bug the author to publish it
4121 error 404 It was specified as a dependency of 'gulp-sourcemaps'
```
Yesterday it worked

**Comment by boxcee** [comment]
Duplicate of [Issue 292](https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/292)

**Comment by qrpike** [comment]
Getting same issue

**Comment by nmccready** [comment]
Closing due to dupe; please if your having proxy problems roll back your version. Use stricter versioning, npm shrinkwrap or yarn.lock .

**Comment by phated** [comment]
Or a better proxy ;)

**Comment by phated** [comment]
If you are using `sinopia`, you probably want to switch to https://github.com/verdaccio/verdaccio
