### ISSUE TITLE
Dependency error when doing npm install

### ISSUE THREAD

**Issue by Chengxuan** [gulp-sourcemaps/gulp-sourcemaps#294]
We encountered this error when do npm install with gulp-sourcemaps 2.5.0 dependency:
```
npm ERR! 404 Not Found: artifactory
npm ERR! 404 
npm ERR! 404  'artifactory' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
```

**Comment by Chengxuan** [comment]
duplicated with #292 , our registry doesn't support scope.

**Comment by phated** [comment]
If you are using `sinopia`, you probably want to switch to https://github.com/verdaccio/verdaccio

**Comment by wiktor256** [comment]
You can try adding: `@gulp-sourcemaps:registry="http://registry.npmjs.org/"` to your `.npmrc`. This will bypass your registry for this particular package.
