### ISSUE TITLE
Dependency issue with 1.12.0

### ISSUE THREAD

**Issue by saumyatripathi** [gulp-sourcemaps/gulp-sourcemaps#295]
Hi - I would like to first thank you for creating this. I'd like to report an issue that I've been facing this morning while trying to push my build to server (using a CI tool). The build workflow involves getting all the npm packages into an empty folder (which means all of them are re-downloaded). 
My dependency for "gulp-sourcemaps" was set to "^1.5.0" which I assume was trying to get 1.12.0 that was recently release and kept breaking with following error -

```
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code E404
npm ERR! 404 no such package available : @gulp-sourcemaps/map-sources
npm ERR! 404 
npm ERR! 404 '@gulp-sourcemaps/map-sources' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
```

I'd be happy to provide any additional information you may need to investigate this. For now, I have set the version to "1.11.1" which fixed my issue.

**Comment by phated** [comment]
Please use the search function, there are plenty of these issues that have already been closed.  You are using an old version of npm or you are using a proxy that is old and doesn't support scoped packages.

**Comment by phated** [comment]
If you are using `sinopia`, you probably want to switch to https://github.com/verdaccio/verdaccio
