### ISSUE TITLE
You broken your dependencies

### ISSUE THREAD

**Issue by mjangstadt** [gulp-sourcemaps/gulp-sourcemaps#296]
whatever this gulp-sourcemaps/map-sources garbage is in _before_ 2.5.0 it's a bad pointer, breaks usage...also you should major version tag BEFORE you check in major version changes....helps :)

**Comment by phated** [comment]
No, you are using a broken, ancient workflow that is not our job, nor the job of semver, to fix. Upgrade your npm or fix your proxy. Scoped packages have been out for almost 2 years.

**Comment by mjangstadt** [comment]
Regardless, you are making a breaking change and knew enough to bump major version...BUT you need to tag on or before the updates otherwise "^1.x.x" will pull in your breaking changes...it's that simple.
 
http://semver.org/

**Comment by nmccready** [comment]
@mjangstadt please target 1.11.X or 2.14.X which is safer and then work on a migration path.  Semver was followed (debatable if this should have been a major bump vs minor). 

Regardless your version requirements are way too loose in npm/yarn.

Use a lock file shrinkwrap and or yarn.lock and you would have avoided this. It is not our responsibility to preach best practices.

**Comment by phated** [comment]
@mjangstadt you are confused what semver is for.  It is for API breaking changes, none of which were made.  Please understand your tools before making claims that you don't fully understand.

@nmccready it should __not__ have been a major bump, as semver compliance does not say anything about people's non-standard environments causing them to fail to install a dependency.  By following all standard practices, everything is fine with this change.

**Comment by nmccready** [comment]
To clear for everyone
> it should not have been a major bump
I don't disagree with @phated decision; I am speaking from a view point of the community as a whole not agreeing. 

In reality this is a dependency change with no major api changes except minor api modifications.

**Comment by phated** [comment]
If you are using `sinopia`, you probably want to switch to https://github.com/verdaccio/verdaccio
