### ISSUE TITLE
npm ERR! user developers is not allowed to access package @gulp-sourcemaps/map-sources : @gulp-sourcemaps/map-sources

### ISSUE THREAD

**Issue by tamirUtab** [gulp-sourcemaps/gulp-sourcemaps#297]
Hi Guys,

Have you ever encountered this issue - I'm dealing with it for 48 hours ... 

> jpegtran-bin@3.2.0 postinstall /var/lib/jenkins/workspace/musichords/public/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-jpegtran/node_modules/jpegtran-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module '@gulp-sourcemaps/map-sources'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/musichords/public/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

> gifsicle@3.0.4 postinstall /var/lib/jenkins/workspace/musichords/public/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-gifsicle/node_modules/gifsicle
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module '@gulp-sourcemaps/map-sources'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/musichords/public/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm WARN optional dep failed, continuing imagemin-jpegtran@4.3.2

> optipng-bin@3.1.2 postinstall /var/lib/jenkins/workspace/musichords/public/node_modules/grunt-contrib-imagemin/node_modules/imagemin/node_modules/imagemin-optipng/node_modules/optipng-bin
> node lib/install.js

module.js:338
    throw err;
          ^
Error: Cannot find module '@gulp-sourcemaps/map-sources'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/var/lib/jenkins/workspace/musichords/public/node_modules/vinyl-fs/node_modules/gulp-sourcemaps/index.js:6:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
npm WARN optional dep failed, continuing imagemin-gifsicle@4.2.0
npm WARN optional dep failed, continuing imagemin-optipng@4.3.0
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_0.12.9/bin/node" "/var/lib/jenkins/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/NodeJS_0.12.9/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code E403

npm ERR! user developers is not allowed to access package @gulp-sourcemaps/map-sources : @gulp-sourcemaps/map-sources

Thank's ahead

**Comment by cschuff** [comment]
Same issue here. Seems to be introduced with 2.5.0

BR
Chris

**Comment by gonlliuk** [comment]
I have the same issue! Yesterday i have got a npm error:
npm ERR! 404 no such package available : @gulp-sourcemaps/map-sources

I am using private repository which redirect request to npm default registry for public packages and from yesterday this redirect returns a "not found" error.

**Comment by David-Crty** [comment]
I'm using npm in the simplest way but I have also this issue :

> npm info postuninstall gulp-sourcemaps@1.12.0
npm ERR! 404 Not Found
npm ERR! 404 
npm ERR! 404 'gulp-sourcemaps/map-sources' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

**Comment by tamirUtab** [comment]
Hi @gonlliuk and @David-Crty  it is not exactly the same issue sense you guys got 404 instead of our 403 have you tried this solution https://github.com/storybooks/react-storybook/issues/15 ? 
hope you can find assistance as well.

**Comment by cschuff** [comment]
@tamirUtab You are right. I haven't had the same issue. Issue was down to sinopia not supporting scoped packages.

Thanks
Chris

**Comment by gonlliuk** [comment]
@cschuff  How did you solved problem with sinopia and scoped packages? One day ago all was fine =)

**Comment by cschuff** [comment]
@gonlliuk sinopia DOES support scoped packages you just have to configure it right.
Solution here: https://github.com/rlidwka/sinopia/issues/376#issuecomment-195497794

**Comment by CelesteGH** [comment]
Be aware; if you are using nexus prior to version 3.0, scopes are not supported. [http://www.sonatype.org/nexus/2015/11/19/new-npm-tools-for-your-nexus-repository-manager-tool-box](http://www.sonatype.org/nexus/2015/11/19/new-npm-tools-for-your-nexus-repository-manager-tool-box)

**Comment by David-Crty** [comment]
Yeah, anyway i update my npm version to 4.4.4 and it works 👍 
`sudo npm install -g npm`

**Comment by tomsowerby** [comment]
Same issue here using Artifactory since 2.5 and 1.12. Seen with both yarn and npm.

**Comment by shobhitsharma** [comment]
This has to do with the [new scope change](https://docs.npmjs.com/misc/scope) from npm which might not be supported with private npm registry, unless you configure it. 

To patch/resolve this without losing time, replace this to your package.json with version tag before this change.
```
"gulp-sourcemaps": "git@github.com:gulp-sourcemaps/gulp-sourcemaps.git#v${VERSION}"
```

**Comment by phated** [comment]
This has already been discussed plenty of times in other issues. Please use the search function. Either you are using an ancient npm, an ancient proxy for npm that doesn't support scoped packages or your proxy isn't configured correctly. Please fix your environment.

**Comment by mobrien** [comment]
Broken in latest yarn 0.21.3 also.
