### ISSUE TITLE
npm ERR! Invalid name: "@gulp-sourcemaps/map-sources"

### ISSUE THREAD

**Issue by Sarajendran** [gulp-sourcemaps/gulp-sourcemaps#298]
I am getting invalid name error when i run below command to install gulp-sourcemap.
Command:-
```sh
 $  npm install gulp-sourcemaps --save
```

<img width="686" alt="screen shot 2017-04-03 at 2 03 43 pm" src="https://cloud.githubusercontent.com/assets/13481014/24601474/ad82cb96-1876-11e7-975d-08496c68c31b.png">

For more information, I have mentioned below npm and & node version installed on the mac.

| software | version |
| ------ | ------ |
|node |6.10.1||
npm  |3.10.10|

**Comment by Sarajendran** [comment]
I have mentioned below package.json using in the application
```sh
{
  "name": "core",
  "version": "0.0.2",
  "description": "Core Library (Typescript Version) for mobile application",
  "author": "MA",
  "main": "./src/index.ts",
  "license": "MIT",
  "repository": "",
  "publishConfig": {
    "registry": ""
  },
  "keywords": [
    "core"
  ],
  "scripts": {
    "gulp": "gulp",
    "start": "npm install && gulp build-package",
    "karmatest": "karma start karma.conf.js",
    "package": "npm install && gulp npm-package"
  },
  "dependencies": {
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12",
    "es6-promise": "^4.0.5",
    "es6-shim": "^0.35.1",
    "reflect-metadata": "^0.1.8"
  },
  "devDependencies": {
    "browserify": "^13.1.1",
    "del": "^2.2.1",
    "gulp": "^3.9.1",
    "gulp-load-plugins": "^1.2.4",
    "gulp-rename": "^1.2.2",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-tslint": "5.0.0",
    "gulp-typedoc": "^2.0.0",
    "gulp-typescript": "2.13.0",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.3.10",
    "jasmine-core": "2.4.1",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^0.2.3",
    "karma-coverage": "^1.1.0",
    "karma-htmlfile-reporter": "^0.2.2",
    "karma-jasmine": "^0.3.8",
    "karma-junit-reporter": "1.1.0",
    "karma-phantomjs-launcher": "1.0.1",
    "karma-sourcemap-loader": "^0.3.7",
    "karma-verbose-reporter": "^0.0.3",
    "merge2": "1.0.2",
    "phantomjs-polyfill": "0.0.2",
    "remap-istanbul": "^0.6.4",
    "require-dir": "0.3.0",
    "run-sequence": "1.2.2",
    "shelljs": "0.7.3",
    "systemjs": "^0.19.39",
    "tsify": "^2.0.2",
    "tslint": "^3.15.1",
    "typedoc": "0.5.0",
    "typescript": "2.0.2",
    "typings": "^1.3.2",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0"
  }
}

```

**Comment by kirtamus** [comment]
Are you using any form of private/caching npm server?

__@gulp-sourcemaps/map-sources__ is a scoped package, if you are using a private/caching npm server (like __sinopia__) you may find that it does not support scoped packages. https://github.com/rlidwka/sinopia/issues/278

Try running ```npm i gulp-sourcemaps/map-sources``` as a quick fix, but you may want to consider upgrading your private/caching npm server (if you are using one). https://github.com/verdaccio/verdaccio

**Comment by uniquelau** [comment]
Also seeing the issue here too. +1

**Comment by Sarajendran** [comment]
@theKirt : No, I am not using any form of private/caching npm server.

**Comment by phated** [comment]
Yes you are. Fix your environment.

**Comment by Sarajendran** [comment]
@phated : Please don't close the ticket simply. Please do investigate on the issue and find the solution before you close.

I found the issue. It seems "gulp-sourcemaps": "^1.6.0" is not working with this release version. whereas it works for 2.4.1.

please do change the version as below in the package.json 
"gulp-sourcemaps": "2.4.1",

**Comment by phated** [comment]
@Sarajendran I know your problem and this is a duplicate.  I'm sorry you don't understand semver but this is not a place for me to teach it to you.  Locking this.
