### ISSUE TITLE
Between 1.11.1 and 1.12.0 a new dependency was added that fails npm install

### ISSUE THREAD

**Issue by jckellwork** [gulp-sourcemaps/gulp-sourcemaps#304]
The dependency in question is `"@gulp-sourcemaps/map-sources": "1.X"`.  My npm version is 2.15.5 which I think came with Node 4.4.5.  It is possible that I need to do something to define `@gulp-sourcemaps` as a scope I have permission to access.  So maybe it is just me having the problem because I don't know what that *something* is.

**Comment by jckellwork** [comment]
Just to be sure it wasn't my older version of npm I tried with 4.4.4 and I see the same issue so I'm pretty sure I must not have access to that scoped dependency.

**Comment by phated** [comment]
You are using an extremely outdated (or misconfigured) proxy. Please use search, there's a ton of issues exactly like this already answered in the same way.
