### ISSUE TITLE
How to get contents of the `file.sourceMap` object?

### ISSUE THREAD

**Issue by garside** [gulp-sourcemaps/gulp-sourcemaps#305]
I'm trying to upload the file to sentry, but the `file.sourceMap` object doesn't interact with the `request` library in a way I'd expect.

```js
var sourceMap = file.sourceMap;

request.post({
  // Sentry requires a trailing slash on their URLs
  uri: uploadPath.join('/') + '/',
  headers: {
    'Content-Type': 'application/json'
  },
  auth: {
    bearer: options.apiKey
  },
  formData: {
    file: ...,
    name: (options.domain || '') + '/' + slash(sourceMap.file) + '.map'
  }
});
```

So far I've tried

```js
sourceMap.toString() // '[Object object]'
JSON.stringify(sourceMap) // full blob of source map data
new Buffer(sourceMap) // Buffer < 12, 15, 24, ... >
```

None of these seem to work.

Any advice on what I should be doing to this sourceMap object to get it's contents in a way that they can be uploaded to an external server would be amazing. Thanks!

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
