### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by dmitrybelyakov** [gulp-sourcemaps/gulp-sourcemaps#306]
Trying to install with `npm install gulp-sourcemaps --save` gives me this:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp-sourcemaps" "--save"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9

npm ERR! Invalid name: "@gulp-sourcemaps/map-sources"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!    npm-debug.log
```

**Comment by dmitrybelyakov** [comment]
After node update:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "gulp-sourcemaps" "--save-dev"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0

npm ERR! Invalid name: "@gulp-sourcemaps/map-sources"
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     2017-04-22T13_59_12_762Z-debug.log
```

**Comment by dmitrybelyakov** [comment]
Not using any proxies or private repos like `senopia`

**Comment by dmitrybelyakov** [comment]
Is there a way I can find out if I am using a proxy that I'm not aware of? I certainly did not set one up, but having tried everything else from the other similar tickets, which there are plenty of, I still wasn't able to resolve it.

**Comment by phated** [comment]
I think you can list your npm configuration. Maybe someone is proxying between you and npm?

**Comment by dmitrybelyakov** [comment]
Hi,

There is nothing in npm config that suggest using I am using anything other than registry.npmjs.org. Here is a gist of config (also it's a fresh default install): https://gist.github.com/dmitrybelyakov/fd55f9751021a2cb3ecf2e1cd4e300f9

I also tried to connect from different providers in case someone was proxying in between, but still unable to install.

**Comment by dmitrybelyakov** [comment]
I'm not gonna be a 🔔 🔚  like that other guy and actually try to help others:

If you guys are on mac and using .pkg install from nodejs.org - try switching to homebrew version. 
It seems gulp-sourcemaps won't install when using official distribution.
