### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by dmitrybelyakov** [gulp-sourcemaps/gulp-sourcemaps#307]
Not sure why you closed my original issue. Seems like a 'works for me' situation, but obviously, a lot of people are having the same issue:

https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/306

I followed all your recommendations from other people's tickets but still unable to install.

**Comment by phated** [comment]
Your environment is messed up. This isn't the place to track that sort of issue. Scoped modules have been out for 2 years. Continued issues will result in a ban.

**Comment by dmitrybelyakov** [comment]
Sure, let's just ignore everyone. Maybe they'll go away.
