### ISSUE TITLE
meet trouble when using sourcemaps with gulp-babel and gulp-uglify

### ISSUE THREAD

**Issue by fenglinzeng** [gulp-sourcemaps/gulp-sourcemaps#312]
Here is my demo code.

https://github.com/fenglinzeng/gulp-sourcemap-babel-error-code

When I use babel and uglify, looks like sourcemap can not locate the correct console code line.

Is there any error of my usage?

thx.

**Comment by phated** [comment]
Support questions should be directed to StackOverflow.
