### ISSUE TITLE
no such package available : @gulp-sourcemaps/map-sources

### ISSUE THREAD

**Issue by dongyingzi** [gulp-sourcemaps/gulp-sourcemaps#314]
Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "--save-dev" "gulp-sourcemaps"
npm ERR! node v7.2.0
npm ERR! npm  v3.10.9
npm ERR! code E404

npm ERR! 404 no such package available : @gulp-sourcemaps/map-sources
npm ERR! 404 
npm ERR! 404  '@gulp-sourcemaps/map-sources' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by trickydisco78** [comment]
I get the exact same error (using a mac)

**Comment by phated** [comment]
Use the search functionality

**Comment by clubajax** [comment]
What in the heck does that mean?
