### ISSUE TITLE
Memory/performance issues

### ISSUE THREAD

**Issue by stevehipwell** [gulp-sourcemaps/gulp-sourcemaps#316]
When using `gulp-sourcemaps` inside a gulp watch task we are seeing an exponential increase in memory use and time taken for the task. This behaviour is exhibited if we use `gulp-typescript` or if we manually call `tsc` and then load the files to copy the js and map files to the required destination.

**Comment by nmccready** [comment]
So your saying your seeing the same problems as tsc with sourcemaping turned on?

If so this sounds like a typescript or sourcmap problem itself.

**Comment by stevehipwell** [comment]
@nmccready what I'm saying is that when I want to concatenate ts files together and generate a sourcemap using gulp-sourcemaps I have a major performance and memory issue. I have tried two aproaches; the full gulp approach where I use gulp-typescript and the native tsc approach where I load the tsc generated files into gulp to process them.

**Comment by nmccready** [comment]
Ok, gotcha so problems both way leading to here as an issue. I'm following you now. Can reproduce you issue with a small example and then we can have something to play with?

**Comment by stevehipwell** [comment]
@nmccready I'm not sure how to give you an example to replicate this as our codebase has a large number of files. I guess that if you were to find a large typescript project and were to run the following gulp task it would show the issue.

``` javascript
var gulp = require('gulp'),
ts = require('gulp-typescript'),
sourcemaps = require('gulp-sourcemaps'),
gulpFilter = require('gulp-filter'),
concat = require('gulp-concat'),
uglify = require('gulp-uglify');

var tsProject = ts.createProject('tsconfig.json');

gulp.task('watch', function () {
  gulp.watch('src/**/*.ts', ['compile:ts']);
});

gulp.task('compile:ts', function () {
  var tsResult = tsProject.src()
    .pipe(sourcemaps.init())
    .pipe(tsProject());

  return tsResult.js
    .pipe(gulpFilter(['**/*.js', '!**/*.spec.js']))
    .pipe(concat('app.js'))
    .pipe(uglify())
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest('dist/'));
});
```

**Comment by nmccready** [comment]
I know uglify is one of the slower steps have you seen any difference with that gone? You could save uglify for a different task. 

Also try debugging everything with `--inspect` via Node >= 6.

**Comment by stevehipwell** [comment]
@nmccready I meant to remove uglify from there as it has no impact on the delta it just makes all runs take slightly longer.

**Comment by phated** [comment]
This is a known problem with `gulp.watch` and not a problem with gulp-sourcemaps.

**Comment by nmccready** [comment]
@phated thanks for the info. Do you have an existing issue in gulp or a url to reference to this ticket?

**Comment by phated** [comment]
It all falls under "File watcher has problems" https://github.com/gulpjs/gulp/issues/651

**Comment by nmccready** [comment]
@stevehipwell bottom line try out gulp 4 .

**Comment by BMalaichik** [comment]
@stevehipwell have the same issue.
helped downgrading `gulp-sourcemaps` to 2.5 version.
