### ISSUE TITLE
Loading maps causes increasing time of task when running multiple times through watch

### ISSUE THREAD

**Issue by ZoolWay** [gulp-sourcemaps/gulp-sourcemaps#317]
I have a rather large project with TypeScript which included a `gulp.watch` task to monitor for change in the TypeScript source files and trigger the build task accordingly.

Recently (but I cannot point exactly) it started to need more time from compilation to compilation, starting with approx. 12s, then, 18s, 27s, 33s, 38s, and so on. Canceling the running gulp instance and restarting it on the command line restarts the compilation times.

When I turn off loading of sourcemaps (`sourcemaps.init({loadMaps:false})`), this does not happen and compile times stay the same.

It tried to reproduce it with a small sample project but without luck. I profiled it with the Chrome debugger for NodeJS and can say that somewhere in `debug.js/selectColor` the times increase because the parameter `namespace` gets longer and longer on each iteration which affects the calculation of the hash.

For now I can work with the deactivated loading of sourcemaps. But can someone give any hint on what is happening? And I would also appreciate a more detailed explanation of what loading the sourcemaps does as I primarly did it because the Aurelia template did it.

Versions:
Node 8.1.2 and 6.5 tested
Gulp 3.91 and 4-alpha tested
Gulp-Sourcemaps 2.6.0
Gulp-TypeScript 3.1.6
TypeScript 2.3.4
Windows 10

**Comment by phated** [comment]
This is super interesting.  We've always chalked the increased compile times to a problem with `gulp.watch` (which I still believe exists), but this seems like something different.

I don't have any time to dig into this currently but I'd love to get a data dump from you.  Please send as much information as you can; including the project or a reproduction if you can.

Thanks!

**Comment by nmccready** [comment]
So this sounds like a possible leak in [visionmedia debug](https://github.com/visionmedia/debug/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20namespace) . It also could be in its wrapper debug-fabulous as well. Guess I could start w/ some tests against debug-fab first and work down.

**Comment by phated** [comment]
@nmccready you might end up writing a complete replacement 😛

**Comment by BMalaichik** [comment]
+1. Got the same issue.
`gulp-sourcemaps` - 2.6
`gulp-typescript` - 3.1.6
`node` - 6.9.1
OS - Windows 10. Also, will check it on Linux a bit later.

tsc compile takes 12 s, gulp compile - 16 (sourcemap write, but OK, quite acceptable).
recompile - 30, 44, 59.

Commented `sourcemap` write pipes & compilation started taking 12 seconds.

**Comment by BMalaichik** [comment]
@phated Seems like `gulp-sourcemaps@2.6` issue
reverted to `2.5` - works fine

**Comment by nmccready** [comment]
> Seems like gulp-sourcemaps@2.6 issue
> reverted to 2.5 - works fine

All of 2.5.X ? Or does it begin to work at 2.5.2?

**Comment by BMalaichik** [comment]
@nmccready just checked `2.5`. Will test tomorrow with more precise versioning

**Comment by BMalaichik** [comment]
@nmccready
version - compile time1/2/3 (seconds)
`2.5` - 14/15/14
`2.5.1` - 15/16/16
`2.5.2` - 25/55/22
`2.6` - 15/39/46/59

**Comment by nmccready** [comment]
Thank you very helpful. BTW can you post your test code. I'd like to add it as a test to the integration section.

**Comment by BMalaichik** [comment]
@nmccready code is pretty simple
```
    private _compile(project: ts.Project, dest: string) {
        let tsResult = project.src()
            .pipe(sourcemaps.init())
            .pipe(project());

        return tsResult.js.pipe(sourcemaps.write({
            includeContent: false, sourceRoot: (file) => {
                const rootPath = (<any>file).history[0].replace((<any>file).base, "").split("\/").map(() => "..").slice(2).join("/");

                return rootPath;
            }
        }))
            .pipe(gulp.dest(dest));
    }
```

`sourceRoot` override impact is poor, tested without it, result is the same.
I use custom wrapper to register TS class methods as gulp tasks

**Comment by ZoolWay** [comment]
Wanted to add my latest observations, just quick checks.

Using version **2.6.0**:
* Active `loadMaps` had terrible impact, see OP
* Deactivating `loadMaps` improved the situation, but compile times still increased from run to run.

After reading the contributions especially by @BMalaichik I switched to **2.5.1**:
* Regardless of `loadMaps: true|false` the compile times stay in the same range and are overall the fastest.

**Comment by nmccready** [comment]
@ZoolWay I am pretty sure I have determined the leak is in debug-fabulous. I am still working on fixing it. I believe it is the spawn function.

**Comment by BMalaichik** [comment]
@ZoolWay 2.51 has leak, but slow down is less comparing to higher versions. `2.5.0` works fine

**Comment by nmccready** [comment]
> @ZoolWay 2.51 has leak, but slow down is less comparing to higher versions. 2.5.0 works fine

So this also could be related to `strip-bom-string` since your seeing issues start at 2.5.1 .
https://github.com/gulp-sourcemaps/gulp-sourcemaps/commit/b6265a87b2c18c38cf5c6a91378eb8a3d0b11e84#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R34

**Comment by phated** [comment]
@nmccready it isn't that...

**Comment by nmccready** [comment]
@phated yeah your right I looked at strip-bom-string 's code and it is minimal. @phated feel free to review my code on debug-fabulous.

**Comment by nmccready** [comment]
Someone test against this branch and let me know if this helps them https://github.com/gulp-sourcemaps/gulp-sourcemaps/tree/nmccready/loggingMemleak

**Comment by jybleau** [comment]
Hello @nmccready , your branch works for me. 
Consistent execution time during watch task with loadMaps = true.
Thanks!

**Comment by rsxdalv** [comment]
Will this get released?

**Comment by nmccready** [comment]
I work on releasing it; there might still be an issue as travis failed somewhere.

**Comment by nmccready** [comment]
Done 4b723f0253cf089db09d8f209a5a374394c4c185

**Comment by nmccready** [comment]
Rebuilt and it went away.
