### ISSUE TITLE
Intermediate CSS file listed as source in external sourcemap when used with sass/clean-css and having attribute selector in input

### ISSUE THREAD

**Issue by mtter** [gulp-sourcemaps/gulp-sourcemaps#319]
I'm trying to compile SASS files (using gulp-sass) and then minimize the CSS output (using gulp-clean-css) while generating external source maps with what I think is pretty much a vanilla setup along the lines described in the documentation. 
```
gulp.task('minimal', function() {
	return gulp.src(['./minimal*.scss'])
        .pipe(sourcemaps.init())
        .pipe(sass())
	.pipe(cleanCSS())
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest('out'));
})
```
I checked that both plugins I'm using have sourcemaps support (https://github.com/gulp-sourcemaps/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support).

In general, this setup seems to work well. I just came across the following issue with a specific SCSS input however:

It seems that, in cases where the input SCSS file contains an attribute selector (e.g. `[dir=rtl]`), the intermediate CSS file is added to the list of sources in the resulting external source map file. With other inputs, just the source SCSS files are added to the sources list as expected:
```
{"version":3,"sources":["minimal-attribute.css","minimal-attribute.scss"],"names":[], ...
```
as opposed to
```
{"version":3,"sources":["minimal-class.scss"],"names":[],...
```
 I think adding a file that never existed on the file system to the sources list is wrong and should not happen in either case.

When viewing the sourcemap in Chrome, the excess file is shown in the sources tab but no contents are shown when one tries to open it.

I set up a minimal example here:
https://github.com/mtter/sourcemaps-minimal

It processes two similar (quite minimal) SCSS file using the pipeline above. Both files contain one single (identical) SCSS rule, once with a class selector and once with an attribute selector. The resulting sourcemaps should show the difference described above.

Any help with this would be very much appreciated.

**Comment by phated** [comment]
I've looked at this and it's a bug with gulp-clean-css.  They are setting the previous sourcemap on the options for clean-css (at https://github.com/scniro/gulp-clean-css/blob/master/index.js#L23-L25) which generates the invalid sourcemap.  Please raise your issue with gulp-clean-css
