### ISSUE TITLE
install produces errors related to gulp-sourcemaps/identity-map' is not in the npm registry

### ISSUE THREAD

**Issue by waaps** [gulp-sourcemaps/gulp-sourcemaps#321]
info trying registry request attempt 1 at 5:45:28 PM
http GET https://registry.npmjs.org/gulp-sourcemaps
http 304 https://registry.npmjs.org/gulp-sourcemaps
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/convert-source-map
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/css
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/acorn
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/strip-bom-string
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/debug-fabulous
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/detect-newline
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/source-map
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/through2
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/vinyl
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/gulp-sourcemaps/identity-map
info trying registry request attempt 1 at 5:45:29 PM
http GET https://registry.npmjs.org/gulp-sourcemaps/map-sources
http 304 https://registry.npmjs.org/convert-source-map
http 304 https://registry.npmjs.org/acorn
http 304 https://registry.npmjs.org/debug-fabulous
http 304 https://registry.npmjs.org/css
http 304 https://registry.npmjs.org/detect-newline
http 304 https://registry.npmjs.org/source-map
http 304 https://registry.npmjs.org/through2
http 304 https://registry.npmjs.org/vinyl
http 304 https://registry.npmjs.org/strip-bom-string
http 404 https://registry.npmjs.org/gulp-sourcemaps/identity-map
http 404 https://registry.npmjs.org/gulp-sourcemaps/map-sources
npm ERR! 404 Not Found
npm ERR! 404
npm ERR! 404 'gulp-sourcemaps/identity-map' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it
npm ERR! 404 It was specified as a dependency of 'gulp-sourcemaps'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, or http url, or git url.

npm ERR! System Windows_NT 10.0.14393
npm ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "gulp-sourcemaps"
npm ERR! cwd C:\Users\Ken
npm ERR! node -v v6.11.0
npm ERR! npm -v 1.4.28
npm ERR! code E404
npm ERR! not ok code 0

**Comment by phated** [comment]
Please use the Github search feature. This has been reported and closed many times.

**Comment by waaps** [comment]
I did search on it and the explanation was never made clear. As someone new
to node, it is impossible to decipher from a handful of disjointed
sentences the actual step by step way to fix the issue. Please walk through
step by step the process to get it to work. Screen captures or copy paste
from the command line is best.
Thanks

On Jul 10, 2017 6:12 PM, "Blaine Bublitz" <notifications@github.com> wrote:

Please use the Github search feature. This has been reported and closed
many times.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/321#issuecomment-314264820>,
or mute the thread

**Comment by Toltar** [comment]
@phated I am facing similar issues. I have searched and searched, but cannot find it. I know as a maintainer you have to keep the issues board clean and free of duplicates. Might I suggest if this has been brought up and resolved, please reference the issue that the problem has been resolved in. It will be much more helpful and you will get less people opening issues on this so you don't waste time closing duplicates. My node environment works on other packages other than this one(I isolated it by not including this package and it works). I am just getting the error either its the identity-map that is screwing up or map-sources like the example below:

```
npm ERR! node v6.11.1
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@gulp-sourcemaps/map-sources"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]
```

So if you have an issue that you can reference to solve this, please do.

P.S. Thanks @phated for your great work with gulp. 👍 I just started using it, and I have to say its been a pleasure working with it. I will definitely will be using it in personal projects.

**Comment by phated** [comment]
@Toltar Thank you for the kind words. Your environment is using a proxy (likely using sinopia - a package that hasn't been updated in forever and I believe it gets forced installed by yarn and maybe other facebook projects).  Neither of the projects you reference are screwing things up, your environment  is the thing that got messed up to not support a feature this npm feature (which has existed for 2+ years).  You can find this answer many more times at https://github.com/gulp-sourcemaps/gulp-sourcemaps/search?utf8=%E2%9C%93&q=map-sources&type=Issues

**Comment by Toltar** [comment]
@phated Ahh I see. Thanks for reporting this, it's was very helpful. I am not sure if we have that package you speak of(since it's on a build server), but I will definitely be bringing this up to my colleagues. Sorry if I didn't give a detailed log of the NPM because some of this info is sensitive since I work for a government agency. I will be glad to provide a solution on this ticket if me and my coworkers find one. Again thanks for your answer.

**Comment by waaps** [comment]
@phated (deep breath) I know it is not your job to teach those of us who are newer to NPM than you how to use NPM, however, I have tried to do what you have described and it is not working. I am running a local NPM environment without sinopia or other proxy (is there a way to verify this?). 

All I am doing in going to the NPM site and installing packages of which GULP happens to be a requirement and is failing due to the whole versioning thing. I know it is a lot to ask, but given the long history and large number of users that would benefit, PLEASE help us. A simple step-by-step procedure would go a long way in addressing the issue, and it would get us up to the same versioning capability you are encouraging so we can be compatible. Thanks in advance.

**Comment by lukaszlukasiewicz** [comment]
Maybe this will help someone in the future. Got the same problem as waaps. The problem was old version of npm (npm -v and got 1.4.9). After installing node the version did not change. There was more than one node installation ("where.exe npm" and found node installed by chocolatey). 

this thread helped https://github.com/npm/npm/issues/14015
