### ISSUE TITLE
Weird syntax in `dependencies` breaks Artifactory

### ISSUE THREAD

**Issue by hon2a** [gulp-sourcemaps/gulp-sourcemaps#322]
We have a local Artifactory which we have to use, as it hosts our private packages, but we can't update to the latest version of `gulp-sourcemaps` with it. It seems that the problem is in the following syntax in the `package.json` file:

```
"dependencies": {
  "@gulp-sourcemaps/identity-map": "1.X",
  ...
}
```

I haven't been able to find any mention of such syntax in NpmJS documentation (what does it do?), but more importantly it prevents Artifactory from properly parsing the file. Please fix the syntax if at all possible.

**Comment by nmccready** [comment]
First search on google: https://docs.npmjs.com/getting-started/scoped-packages

This issue comes up daily, please search github old closed issues.

Update your npm on artifactory and it's dependencies. Also use a newer npm.

**Comment by hon2a** [comment]
> First search on google: https://docs.npmjs.com/getting-started/scoped-packages

Didn't find it when I only knew the syntax. And yeah, I did forget to remove `is:open` when searching the issues.

Thanks for the link and sorry for taking up your time.
