### ISSUE TITLE
Autoprefixer is causing problems with sourcemaps when imports are wrapped in a class

### ISSUE THREAD

**Issue by stephenbe** [gulp-sourcemaps/gulp-sourcemaps#324]
Here is my test case : 
https://github.com/stephenbe/sourcemap-bug

Basically if you have autoprefixer and imports that are wrapped by a class : 
```
.random-class {
    display: flex;
    @import "box";
    @import "inbox";
}

```

**Instead of getting :** 
![image](https://user-images.githubusercontent.com/3018441/28382545-7a16d9b8-6c8c-11e7-8b7e-3c4548686dc7.png)

**I am getting this :** 
![document_-_chromium_portable_2017-07-19_14-07-19](https://user-images.githubusercontent.com/3018441/28382428-09b73924-6c8c-11e7-8db2-d07ae828d104.png)

**Comment by davorpeic** [comment]
Have the same issue, and already breaking my head for few hours over this..

This is the closest I found related to this issue https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/60, but still cant get sourcemap passed to final end file

**Comment by Safe-Mode** [comment]
Are there any solutions yet?

**Comment by Shaker-Hamdi** [comment]
I have the same issue. the workaround I did is to enable "Autoprefixer" extension in VSCode on save and removing gulp-autoprefixer in the gulp file so that I can have both source-maps working and have the css autoprefixed.
It makes the SCSS file ugly though. but at least it works.

**Comment by stephenbe** [comment]
@nmccready Hi, I was wondering if there was any update on this issue. I see you put in "in progress". Thank you so much!

**Comment by stephenbe** [comment]
I have good news, I finally found a way to fix this.

package.json
```
{
  "name": "sourcemap-bug",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "gulp-filter": "^5.1.0",
    "gulp-postcss": "^8.0.0",
    "gulp-sass": "^4.0.2",
    "gulp-sourcemaps": "^2.6.5",
    "autoprefixer": "^9.4.10",
    "gulp": "^4.0.0"
  }
}

```

File Structure
![image](https://user-images.githubusercontent.com/3018441/53986567-889d9900-40ec-11e9-8eac-991825fc2373.png)

Gulpfile : 

```
var gulp = require("gulp");

gulp.task("css", function() {
  var sass = require("gulp-sass");
  var postcss = require("gulp-postcss");
  var sourcemaps = require("gulp-sourcemaps");
  var autoprefixer = require("autoprefixer");
  var filter = require("gulp-filter");

  return gulp
    .src("./test.scss")
    .pipe(sourcemaps.init())
    .pipe(sass().on("error", sass.logError))
    .pipe(sourcemaps.write("."))
    .pipe(gulp.dest("./"))
    .pipe(filter("./*.css"))
    .pipe(postcss([autoprefixer({ browsers: ["last 1 major versions, last 3 Chrome versions, ie 11"] })]))
    .pipe(gulp.dest("./"));
});
```
So in the css task I start by creating my map files. Then, I filter all the maps to only use the css files so autoprefixer only prefixes the css files.

This works and i'm closing this issue.

**Comment by phated** [comment]
@stephenbe Awesome!!!! Thanks for posting your solution.  In the above example, you can totally just use the built-in sourcemap support in gulp4 and it should work wonderfully.  Check out the docs: https://gulpjs.com/docs/en/api/src#sourcemaps

**Comment by stephenbe** [comment]
@phated oh ok awesome thanks! We are still using gulp 3 here, but thanks for the info!

**Comment by Alecto** [comment]
Check out the docs: https://gulpjs.com/docs/en/api/src#sourcemaps
doesnt work for scss

**Comment by stephenbe** [comment]
@alecto it actually does work I just tried it, but the same problem occurs that it doesn't show the right file when I enable sourcemaps.

**Comment by Alecto** [comment]
![image](https://user-images.githubusercontent.com/8464662/53988660-b0acec80-412c-11e9-9740-fd0459cb329f.png)
![image](https://user-images.githubusercontent.com/8464662/53988667-b7d3fa80-412c-11e9-96a1-a7c98a696409.png)

look like works.
my mistake - i forgot sourcmap in src
![image](https://user-images.githubusercontent.com/8464662/53988696-cb7f6100-412c-11e9-88e8-a49372779154.png)

thanks

**Comment by stephenbe** [comment]
Is your sass import wrapped in a class ? From my side it doesn't show the writing sass file

**Comment by Alecto** [comment]
Sorry, maybe I did not quite understand your question.
I do not store functions (tasks) in my gulpfile.js, they are all in external files, including configs of the paths.
therefore, I have resulted here only in a part of one of the modules where corrections were necessary. 
otherwise, everything works as standard, without packaging into objects.
if I understand you correctly, sorry for my english.

**Comment by stephenbe** [comment]
No worries. Well this issue is about having this sass : 
```
.test {
 @import "buttons.scss"
}
```

then when I inspect a button in chrome it just shows the file it's importing it in instead of showing _buttons.scss.

@phated should I open an issue with gulp about this?

This is my gulpfile with the new syntaxe

```
var gulp = require("gulp");

gulp.task("css", function() {
  var sass = require("gulp-sass");
  var postcss = require("gulp-postcss");
  var sourcemaps = require("gulp-sourcemaps");
  var autoprefixer = require("autoprefixer");
  var filter = require("gulp-filter");

  return gulp
    .src("./test.scss", { sourcemaps: true })
    .pipe(sass().on("error", sass.logError))
    .pipe(postcss([autoprefixer({ browsers: ["last 1 major versions, last 3 Chrome versions, ie 11"] })]))
    .pipe(gulp.dest("./", { sourcemaps: true }));
});
```
![image](https://user-images.githubusercontent.com/3018441/53989434-f9947f00-40f3-11e9-8494-4a49922f4a0d.png)
this should be _import.scss and not test.scss

If I comment out autoprefixer it works. 

At least with [my solution works](https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/324#issuecomment-470679804) in the mean time

**Comment by Alecto** [comment]
ahh ... maybe!
I have not used such code anywhere, so I did not check it.
may be should writing about ther error to the gulp developers?

**Comment by phated** [comment]
@stephenbe you still need the other code, just remove the sourcemap part like:
```js
var gulp = require("gulp");

gulp.task("css", function() {
  var sass = require("gulp-sass");
  var postcss = require("gulp-postcss");
  var sourcemaps = require("gulp-sourcemaps");
  var autoprefixer = require("autoprefixer");
  var filter = require("gulp-filter");

  return gulp
    .src("./test.scss", { sourcemaps: true })
    .pipe(sass().on("error", sass.logError))
    .pipe(gulp.dest("./", { sourcemaps: '.' }))
    .pipe(filter("./*.css"))
    .pipe(postcss([autoprefixer({ browsers: ["last 1 major versions, last 3 Chrome versions, ie 11"] })]))
    .pipe(gulp.dest("./"));
});
```

**Comment by stephenbe** [comment]
Excellent!! this is the best solution anyone that is on gulp 4! Thank you

i'll update my solution
