### ISSUE TITLE
1.7.0 removed from npm registry?

### ISSUE THREAD

**Issue by abmai** [gulp-sourcemaps/gulp-sourcemaps#325]
One of our modules started to break recently seemingly because `gulp-sourcemaps@1.7.0` was no longer in the npm registry. This seems to be an indirect dependency for us so odd that this only started happening lately.

Was version `1.7.0` deleted from the npm registry recently?

**Comment by nmccready** [comment]
yes it was unpublished as mentioned [here ](https://github.com/gulp-sourcemaps/gulp-sourcemaps/commit/2d8c319a5c8477a6e2f27ce42009b0109faa7421) . We could request npm to back publish. But that version I believe does not run anyway.

**Comment by nmccready** [comment]
Can you bump to a newer release of 1.X?

**Comment by abmai** [comment]
Thanks for the answer, @nmccready! This is interesting - looks like it's not a recent thing (unless npm just recently went through with the deletion?). It's not a direct dependency of ours so I'll have to do some work tracking it down.

**Comment by abmai** [comment]
Traced down as an issue in an older version of `mapbox-gl` - all's good now!
