### ISSUE TITLE
What does "Handle large files" mean?

### ISSUE THREAD

**Issue by JasonKleban** [gulp-sourcemaps/gulp-sourcemaps#327]
There's documentation on how to handle large files, but it doesn't give any background on the threshold of "large" and what runtime/output symptom might indicate the necessity for this switch.

**Comment by jcyh0120** [comment]
want to know this, too.

**Comment by nmccready** [comment]
#267 should answer your questions.  It is an option passed down to one of our dependencies. It looks as though it might have been removed. 

https://github.com/gulp-sourcemaps/gulp-sourcemaps/issues/267#issuecomment-289168988
