### ISSUE TITLE
Sourcemaps is not referencing the correct paths

### ISSUE THREAD

**Issue by nagman** [gulp-sourcemaps/gulp-sourcemaps#328]
Hi,

I've recently added [gulp-js-import](https://www.npmjs.com/package/gulp-js-import) to my application in order to import js files in my main script.js file.

I put sourcemaps.init() before, like for any other js compile task, but every error that occurs in my browser is referenced as being part of script.js.

An example:
script.js
`@import 'test.js';`

test.js
`alert(bar);`

My browser's console:
`Uncaught ReferenceError: bar is not defined at script.js:1 `

I've sent an issue report for gulp-js-import, as it could be related to this plugin, but as I don't know how sourcemaps work when used in a gulp pipeline I prefer to report here as well.

Do you have an idea of how to make it work?
A clue on what to add or change in the gulp-js-import plugin?

Thanks

**Comment by phated** [comment]
There's no sourcemap support in the module you linked.  Also, that plugin doesn't follow gulp plugin guidelines so you should not use it.
