### ISSUE TITLE
gulp sourcemaps doesn't update correct after pipe uglify and then gulpRegexp

### ISSUE THREAD

**Issue by hagaytarab** [gulp-sourcemaps/gulp-sourcemaps#330]
hi 
i have problem when i use pipe uglify and then gulpRegexp 
the sourcemap doesnt update correct .

i check in chrome debugging tool and i cant put breakpoint in my js file. if i use only one of them uglify or gulpRegexp it's work ok 
   
    var gulp = require("gulp"),
    concat = require("gulp-concat") ,
    sourcemaps = require('gulp-sourcemaps'),
    uglify = require('gulp-uglify'),
    replaceSourcemaps = require('gulp-replace-with-sourcemaps'),
    gulpRegexp = require('gulp-regexp-sourcemaps');

    gulp.task('default', function () {    
    gulp.src('js/*.js')
    .pipe(sourcemaps.init({ loadMaps: true }))
    .pipe(concat('all.js'))
     //if i remove uglify or gulpRegexp it work fine
    .pipe(uglify())  
    .pipe(gulpRegexp(/(".*?")/g, '$1' + '\n'))
    .pipe(sourcemaps.write(''))
    .pipe(gulp.dest('dist/'));
    });

any idea?

thanks alot

**Comment by nmccready** [comment]
Please use stackoverflow for issues like this.
