### ISSUE TITLE
Installation error 404 Not Found @gulp-sourcemaps…

### ISSUE THREAD

**Issue by linusbostrom** [gulp-sourcemaps/gulp-sourcemaps#332]
Getting this error when I try to install the gulp-sourcemaps package:

`404 Not Found: @gulp-sourcemaps/map-sources@https://registry.npmjs.org/@gulp-sourcemaps/map-sources/-/map-sources-1.0.0.tgz`

Running npm version 5.6.0 and node v.8.9.3

**Comment by phated** [comment]
Please use the search functionality of github, many people before you have experienced this problem and the answers exist there.
