### ISSUE TITLE
speed issue

### ISSUE THREAD

**Issue by lovingcowboy** [gulp-sourcemaps/gulp-sourcemaps#333]
I use gulp-sourcemaps on windows 
` "gulp": "github:gulpjs/gulp#4.0",
    "gulp-autoprefixer": "^4.0.0",
    "gulp-cache": "^0.4.6",
"gulp-sourcemaps": "^2.6.0",`
script
`export function style() {
    return gulp.src(paths.styles.src)
        .pipe(sourcemaps.init({largeFile: true}))
        .pipe(sass().on('error', sass.logError))
        .pipe(autoprefixer({
            browsers: ['last 7 versions'],
            cascade: false
        }))
    .pipe(sourcemaps.write('./maps'))
  .pipe(cached('mysass'))
    .pipe(gulp.dest(paths.styles.temp))
        .pipe(reload({
            stream: true
        }))
}`
It show that with the script`    .pipe(sourcemaps.write('./maps'))` It became slower and slower up to 5 seconds(i change the same file some place again and again to test it) to finished the style() function.It will work fine if i remove it.
[00:25:12] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:13] Finished 'style' after 233 ms
[00:25:14] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:14] Finished 'style' after 319 ms
[00:25:16] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:16] Finished 'style' after 384 ms
[00:25:17] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:18] Finished 'style' after 521 ms
[00:25:19] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:20] Finished 'style' after 690 ms
[00:25:21] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:22] Finished 'style' after 793 ms
[00:25:29] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:30] Finished 'style' after 942 ms
[00:25:31] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:25:32] Finished 'style' after 1.09 s
[Browsersync] File event [change] : css\PESchool.css
[00:26:39] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:26:41] Finished 'style' after 1.38 s
[Browsersync] File event [change] : css\PESchool.css
[00:26:42] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:26:43] Finished 'style' after 1.43 s
[00:26:45] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:26:46] Finished 'style' after 1.32 s
[00:26:47] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:26:49] Finished 'style' after 1.58 s
[00:26:50] Starting 'style'...
[Browsersync] File event [change] : css\common.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\index.css
[Browsersync] File event [change] : css\my.css
[Browsersync] File event [change] : css\PESchool.css
[Browsersync] 8 files changed (common.css.map, commo
css, my.css.map, my.css, PESchool.css.map, PESchool.
[00:26:52] Finished 'style' after 1.83 s
[Browsersync] File event [change] : css\PESchool.css

**Comment by phated** [comment]
Assuming you are on windows...

This is a known, old chokidar issue. https://github.com/paulmillr/chokidar/issues/328
