### ISSUE TITLE
css package dependency causing issues with yarn

### ISSUE THREAD

**Issue by strarsis** [gulp-sourcemaps/gulp-sourcemaps#334]
Related: 
https://github.com/yarnpkg/yarn/issues/1619#issuecomment-352188088

package.json: 
https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/master/package.json#L30

**Comment by phated** [comment]
We are open to adopting a new module that generates CSS sourcemaps but we're not actively working to replace that module to make one unsanctioned package manager work.

Please send a PR if you want to fix this.
