### ISSUE TITLE
gulpjs recommends upgrading of vinyl for dependent plugins due to issues with gulp 4.0.0-alpha.3

### ISSUE THREAD

**Issue by dozer75** [gulp-sourcemaps/gulp-sourcemaps#336]
Refer to gulpjs/gulp#2065 @phated recommend upgrading usage of vinyl to 2.0 or 2.1 and to stop using gulp-util. Due to listing of `npm list` I can see that you are using an old version of vinyl (1.2.0) that they says isn't compatible with gulp 4.0.0.

I can't confirm that this solves my issue, but according to the referenced post it should.

For further discussions I think it's better that you take it directly with the @gulpjs project since I don't know whats exactly is the problem.

**Comment by nmccready** [comment]
Latest release moved vinyl to devDeps https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/master/package.json#L55

**Comment by dozer75** [comment]
I downloaded the latest package but still get the same problem... With the same stacktrace...

**Comment by phated** [comment]
@Dozer, of course you would because it's not this modules fault.

**Comment by dozer75** [comment]
@phated Yes I realized now that even gulp-typescript has the same issue (missed it in my previous npm list query). Together with a bunch of other gulp libraries too. It's a pity that you closed the original post. It makes it problematic to discuss the original issue. But you are right closing this one, it seems that this module doesn't have the problem anymore. vinyl-fs 2.4 and vinyl-file 2.0 uses old vinyl 1.2 and that causes issues in lots of modules...

**Comment by phated** [comment]
There's nothing to discuss, I've already outlined what to do. I don't need to keep receiving people's entitled complaining.
