### ISSUE TITLE
Relative path (./src/init.js and ./src/write.js) doesn't work

### ISSUE THREAD

**Issue by Sascha89** [gulp-sourcemaps/gulp-sourcemaps#337]
Using the latest tag 2.6.2 I get the error, that the init.js and write.js can't be found. The reason for that issue are the relative paths (./src/init.js and ./src/write/.js) in the index.js.

I know that this bug has already been created and closed but for me, this issue still remains.

**Comment by phated** [comment]
Reinstall the package from npm and clean your npm cache.

**Comment by Sascha89** [comment]
Thank you for your help. But I'm sorry, cleaning the cache and reinstalling the packge didn't work. Do you have any other solution for me? 

I guess as long as the index file looks as follows, the module can't work for me because of the relative paths. Am I right with that?:
`

module.exports = {
  init: require('./src/init'),
  write: require('./src/write'),
  mapSources: require('@gulp-sourcemaps/map-sources'),
  identityMap: require('@gulp-sourcemaps/identity-map')
};
`
