### ISSUE TITLE
Sourcemaps not mapping properly

### ISSUE THREAD

**Issue by BusbyActual** [gulp-sourcemaps/gulp-sourcemaps#340]
I'm using gulp and browserify to minify some files for my angularJS application and I'm having some difficulty getting the map files to map properly. 

Chrome gives me : DevTools failed to parse SourceMap: http://localhost:8000/scripts/math.min.map

The pipeline I'm using looks like this:

	gulp.src('./scripts/*.js')
			.pipe(sourcemaps.init({loadMaps: true}))
			.pipe(sourcemaps.write())

I notice there is a debug feature to see where it's breaking. I have a .env file with debug='gulp-sourcemaps:*' and I'm not getting any output. Am I missing something?

**Comment by nmccready** [comment]
The environment variable is `DEBUG` not debug see if that helps.
