### ISSUE TITLE
npm latest version showing 1.12.1

### ISSUE THREAD

**Issue by deedw** [gulp-sourcemaps/gulp-sourcemaps#345]
The latest version on npm seems to have gone backwards - I am currently using version 2.6.4 but the latest version showing on npm is now 1.12.1.

**Comment by nmccready** [comment]
Talk to npm's website tech support its a stupid bug / technicality where it cares about time more than the latest version number. This happens every time I try to be nice and back port a fix to 1.x and pushed 2.x prior.

Theres nothing that can be done until the next release of 2

**Comment by nmccready** [comment]
Ok, aparrently I am wrong and I can use `npm tag` to fix this obscure problem. I'll fix it in a bit.

**Comment by phated** [comment]
I've updated the tags.
