### ISSUE TITLE
Add support for `.mjs`

### ISSUE THREAD

**Issue by demurgos** [gulp-sourcemaps/gulp-sourcemaps#347]
Hi,
Would it be possible to add support for the `.mjs` extension as an alias of `.js`?
I currently have to generate my files as `.js`, write the source maps and then rename to `.mjs` which is bit convoluted.

I believe that you just need to add a `case "mjs":` here (but I am not familiar enough with this lib, there may be other changes required):
https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/492d937ffa0d5aa62a0d5b99ceb7deb2f472c7ad/src/utils.js#L46

**Comment by phated** [comment]
@demurgos this likely would go in https://github.com/gulp-sourcemaps/identity-map

**Comment by nmccready** [comment]
@phated with identity-map, which is awesome. I think `js` and `css` should  be removed from `init`.

**Comment by nmccready** [comment]
I've been thinking on about how to integrate [gulp-postcss](https://github.com/postcss/gulp-postcss/blob/master/index.js) to remove `css`.  

It would be nice to chain filter (css) and then just pump files into gulp-postcss as it's api options are quite nice.

**Comment by nmccready** [comment]
Closing as this should go in identityMap . Also I wonder if it should even be identityMaps responsibility.
Just add a gulp-filter and do something similar to what gulp-postcss is  doing. Another option is to make identityMap more extensible to add on more generators easily.

**Comment by domoritz** [comment]
@demurgos could you describe how you rename files and source maps to generate source maps for `.mjs` and `.cjs` files?
