### ISSUE TITLE
Snyk reports medium severity security vulnerability

### ISSUE THREAD

**Issue by SiAdcock** [gulp-sourcemaps/gulp-sourcemaps#351]
Snyk is currently reporting a [medium severity security vulnerability](https://snyk.io/test/npm/gulp-sourcemaps?severity=high&severity=medium&severity=low) in this library.

> **Introduced through:** gulp-sourcemaps@2.6.4 › css@2.2.1 › source-map-resolve@0.3.1 › atob@1.1.3
> **Introduced through:** gulp-sourcemaps@2.6.4 › @gulp-sourcemaps/identity-map@1.0.1 › css@2.2.1 › source-map-resolve@0.3.1 › atob@1.1.3
> Affected versions of [atob](https://www.npmjs.com/package/atob) are vulnerable to Uninitialized Memory Exposure. It allocates uninitialized Buffers when a number is passed in user provided fields.

I currently have a PR at reworkcss/css#112 to get this fixed, but I'm not too hopeful of it being merged as the project seems abandoned.

Is it worth considering alternatives to `reworkcss/css`? A good contender might be [`NxtChg/pieces/js/css_parser`](https://github.com/NxtChg/pieces/tree/master/js/css_parser), although it's slightly awkwardly packaged.

**Comment by nmccready** [comment]
Hmm, have you tried contacting anyone directly on the rework team? It's possible you might be able to become a member and push that project along. See if @tj can chime in. I know he is busier with Go these days but it's worth a shot. 

Lastly, Post-CSS / AutoPrefixer might be the best option see https://github.com/postcss/postcss#gulp .

**Comment by SiAdcock** [comment]
Thanks @nmccready, good shout. I've sent them an email, I'll let you know what they come back with.

Agreed, PostCSS does seem like a much better option!

**Comment by SiAdcock** [comment]
reworkcss/css#112 has been merged, fixing this security issue.

On a sidenote, @SlexAxton from `reworkcss` told me that the `css` library is effectively unmaintained (excluding security patches) and recommended migrating to PostCSS whenever possible.
