### ISSUE TITLE
uglifycss conflicts

### ISSUE THREAD

**Issue by puggan** [gulp-sourcemaps/gulp-sourcemaps#352]
Made an exemple at:
https://github.com/puggan/gulp-test/commit/819afc7973af69b527cc89fea874433b8d672311

the `all.css.map` file works as expected, referencing to the right less-file.

but the `all.min.css.map` dosn't.
after runing `gulp` the style for header references to b.less.
if i run `gulp re-uglifycss`, the styles all refers to all.min.css

1. Why do the 2 task give different results?
2. What can I do to make the sourcemap work again?

**Comment by nmccready** [comment]
See #349 as I believe this is the same issue.
