### ISSUE TITLE
Skip from generating sourcemaps if exists

### ISSUE THREAD

**Issue by Rajkiran29** [gulp-sourcemaps/gulp-sourcemaps#356]
Hi,
i would like to know if there is an option to skip generating sourcemaps if a soucemaps already exsists on a file.
i am having a scenario of generating typescript sourcemaps and javascript sourcemaps and i don't want to override my typescript sourcemaps

**Comment by phated** [comment]
Well-behaved plugins apply sourcemaps in order so they can be "unwound" by the browser/viewer.  All plugins within the gulp-sourcemaps organization check for a sourceMap property before performing any operations.
