### ISSUE TITLE
es6 and compile to es5, eslint

### ISSUE THREAD

**Issue by nmccready** [gulp-sourcemaps/gulp-sourcemaps#357]
Tired of jshint and I am used to es6 enough of this legacy stuff.

**Comment by phated** [comment]
Please no 😛

**Comment by nmccready** [comment]
Yeah I understand the restraint but if I am going to be the main one maintaining this forward I want modern node with a modern linter. Jshint down right sucks compared to eslint. It's time to move forward. Roll up and or gulp work great to publish this library as es6.

**Comment by coreyfarrell** [comment]
I agree with the idea of moving forward but compiling to ES5 has drawbacks.  It's more difficult for people to test PR's when a module has to be compiled.  Currently it's possible for someone to test a PR by pointing package.json dependency directly to a github branch such as `"gulp-sourcemaps": "gulp-sourcemaps/gulp-sourcemaps#some-branch"`.

Compiling to ES5 also does not solve the issue of dependencies requiring current versions of node.  Example: the current version of eslint requires node.js 6.

**Comment by phated** [comment]
I've spent the time getting gulp set up. Why not just use my set-up?

**Comment by phated** [comment]
Since everyone complains at me, I present #367

**Comment by nmccready** [comment]
Looks good so far to me. Heck if you wanted to rewrite this in ReasonML I’d be fine with that. lol It would be a spot where I could actually fit some time into learn it.

**Comment by coreyfarrell** [comment]
I'm sorry to have come across as complaining to you.  I wasn't aware of the work you did to use eslint in gulp, this looks good.

**Comment by nmccready** [comment]
> I'm sorry to have come across as complaining to you.

@coreyfarrell I am pretty sure he's being sarcastic. Its just the natural progression of being an under appreciated OSS dev. 😅
