### ISSUE TITLE
sourcemaps for automatic created files from postCSS

### ISSUE THREAD

**Issue by kingmauri** [gulp-sourcemaps/gulp-sourcemaps#360]
i'm using the postcss plugin "postcss-extract-media-query". basically is extracts from the compiled styles.css all media queries in separates css files. for example styles-medum.css, styles-large.css etc. my goal is to create source-maps for all these files.

the problem is that is goes out of the gulp flow while creating this files. is there a way or solutions to handle such situations?

thx!!

https://www.npmjs.com/package/postcss-extract-media-query

**Comment by phated** [comment]
It looks like that package touches the filesystem by default.  Maybe you could persuade them to provide an in-memory representation of the new files that you could turn into vinyl files that you re-emit.  I think that would take a bit of rearchitecting though.
