### ISSUE TITLE
Autoprefixer and Sourcemap conflict

### ISSUE THREAD

**Issue by digamber89** [gulp-sourcemaps/gulp-sourcemaps#362]
I see that the wiki currently lists - gulp autoprefix as broken - i've tried to use it with postcss as well but without success.
This is my current implementation:
`gulp.task('compileStyles', function () {

    var plugins = [
        autoprefixer({
            browsers: ['last 2 versions'],
            cascade: false
        })
    ];

    return gulp.src(stylesSource)
        .pipe(plumber({errorHandler: notify.onError("Error: <%= error.message %>")}))
        .pipe(sourcemaps.init())
        .pipe(sass({sourceMap: true, outputStyle: 'compact'}))
        .pipe(postcss(plugins))
        .pipe(sourcemaps.write('./maps'))
        .pipe(gulp.dest('./css'))
        .pipe(uglifycss({
            "maxLineLen": 80,
            "uglyComments": true
        }))
        .pipe(rename({suffix: '.min'}))
        .pipe(gulp.dest('./css'))
        .pipe(notify({message: 'TASK: "styles" Completed! 💯', onLast: true}));
});`

is there any way I can get these two to work together ?

**Comment by phated** [comment]
gulp-postcss with the autoprefixer plugin should work fine.  If there's an issue, you should bring it up with the author of that plugin.
