### ISSUE TITLE
remove restriction on gulp-autoprefixer?

### ISSUE THREAD

**Issue by sol-idsnake** [gulp-sourcemaps/gulp-sourcemaps#379]
I'm going off of the cautionary statement [here](https://github.com/gulp-sourcemaps/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support) (far bottom of the page) that `gulp-autoprefixer` does not retain line information to accurately show sourcemaps.

Sourcemaps seem to work fine with this code:

```
import autoprefixer from 'gulp-autoprefixer';
import browserSync from 'browser-sync';
import gulp from 'gulp';
import minify from 'gulp-clean-css';
import plumber from 'gulp-plumber';
import rename from 'gulp-rename';
import sass from 'gulp-sass';
import sourcemaps from 'gulp-sourcemaps';

gulp.task('styles', done => {
	gulp.src('./_sass/theme.scss')
		.pipe(plumber())
		.pipe(sourcemaps.init({ loadMaps: true }))
		.pipe(sass())
		.pipe(autoprefixer('last 2 versions', '> 5%'))
		.pipe(rename({ suffix: '.min' }))
		.pipe(minify())
		.pipe(sourcemaps.write('./'))
		.pipe(gulp.dest(output))
		.pipe(browserSync.stream());
	done();
});
```

versions:
```
"gulp-autoprefixer": "^7.0.1",
"gulp": "^4.0.2",
"gulp-sourcemaps": "^2.6.5"
```

I don't think this makes setting up gulp with autoprefixer any easier or harder, but if someone can confirm this working it may be time to remove the restriction.

**Comment by phated** [comment]
That wiki just needs to go away. Also, I suggest you fix your gulp syntax if you do further examples in the future: 1. you need to return your stream, not call the done function in a stream-based task (that is all sorts of broken) and 2. gulp 4 already has built-in sourcemap support.
