### ISSUE TITLE
v3 changelog?

### ISSUE THREAD

**Issue by cb1kenobi** [gulp-sourcemaps/gulp-sourcemaps#381]
I see v3.0.0 was published on Nov 11, 2020, but I'm curious what the breaking changes are? I don't see a changelog. There are no releases or v3 tags. I also suspect the master branch may not be in sync with the machine that published v3. 

Can someone fill me in please?

**Comment by nmccready** [comment]
Two Reasons Security Fixes:

- acorn which caused us to drop support for Node < 6 https://github.com/gulp-sourcemaps/gulp-sourcemaps/pull/376/files
- css bump https://github.com/gulp-sourcemaps/gulp-sourcemaps/pull/380

Feel free to PR to make a change log.

**Comment by nmccready** [comment]
Code and Tags have been pushed up. Apologies
