### ISSUE TITLE
Bug: `write` should not compute absoule path of content source code based on `file.base`

### ISSUE THREAD

**Issue by haoadoresorange** [gulp-sourcemaps/gulp-sourcemaps#389]
Hi,

The [README](https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/813c0dac7a0f7bb37cbd7ed7d5020251be823c6a/README.md?plain=1#L359) say

> **Important**: Make sure the paths in the generated source map (`file` and `sources`) are relative to `file.base` (e.g. use `file.relative`).

following how the source code content is loaded [here](https://github.com/gulp-sourcemaps/gulp-sourcemaps/blob/master/src/write/index.internals.js#L79)

> var sourcePath = path.resolve(file.base, sourceMap.sources[i]);

However IMHO the `file.base` should not be used for this purpose since it doesn't always reflect where the source map file is.

In `gulp-typescript` for example, we set `file.base` to be the `outDir` option in `tsconfig.json`. Because `gulp.dest` use `file.relative` for final destination, this is required in order to copy the structure of `src` folder into the compiled folder.

Making the `sources` field relative to `file.base` meaning we're having an incorrect path. If we set it correctly, then `gulp-sourcemaps` can't load the source content.

The suggested solution is to use `path.dirname(file.path)` instead.

EDIT: I see in the README

> `sourceRoot` Set the location where the source files are hosted (use this when includeContent is set to false). This is usually a URL (or an absolute URL path), not a local file system path. By default the source root is '' or in case destPath is set, the relative path from the source map to the source base directory (this should work for many dev environments). If a relative path is used (empty string or one starting with a .), it is interpreted as a path relative to the destination. The plugin rewrites it to a path relative to each source map.

This fixes the problem. But is there a reason for using `file.base` instead of `path.dirname(file.path)` ?
Am I missing something ?

**Comment by phated** [comment]
`file.base` is the path parent before the glob which helps gulp rebuild directory structures in the destination. That is purposefully the default. If you are doing something weird, you should use `sourceRoot` to set your sourceRoot however you want.

**Comment by haoadoresorange** [comment]
I understand the purpose of `file.base`, I'm saying that in this case we don't need to use it. Loading the source content isn't something related to *path parent before glob*.
