### ISSUE TITLE
gulp-rev not in list of supported plugins

### ISSUE THREAD

**Issue by vshih** [gulp-sourcemaps/gulp-sourcemaps#390]
I notice that [gulp-rev](https://github.com/sindresorhus/gulp-rev) is not mentioned in https://github.com/gulp-sourcemaps/gulp-sourcemaps/wiki/Plugins-with-gulp-sourcemaps-support, but it seems it could be.

**Comment by phated** [comment]
That document is entirely out of date. I wouldn't recommend using it and instead look at the plugins themselves.
